
(tool-bar-mode 0)
(menu-bar-mode t)
(show-paren-mode t)
(recentf-mode t)
(electric-pair-mode t)
(global-hl-line-mode t)
(setq history-length 25)
(savehist-mode t)
(save-place-mode t)
(global-hl-line-mode 0)
(global-auto-revert-mode t)
(global-display-fill-column-indicator-mode t)
(fset 'yes-or-no-p 'y-or-n-p)
(toggle-frame-maximized)
(setq inhibit-startup-message t)
(setq make-backup-files nil)
(setq auto-save-default nil)
(setq visible-bell t)
(setq use-dialog-box nil)
(setq global-auto-revert-non-file-buffers t)
(add-hook 'before-save-hook 'delete-trailing-lines)
(add-hook 'before-save-hook 'delete-trailing-whitespace)

(provide 'init-misc)
