
(tool-bar-mode -1)
(menu-bar-mode t)
(show-paren-mode t)
(recentf-mode t)
(electric-pair-mode t)
(global-hl-line-mode -1)
(setq history-length 25)
(savehist-mode t)
(save-place-mode t)
;; (fido-vertical-mode t)
(global-auto-revert-mode t)
(global-display-fill-column-indicator-mode -1)
(fset 'yes-or-no-p 'y-or-n-p)
(toggle-frame-maximized)
(setq inhibit-startup-message t)
(setq make-backup-files nil)
(setq auto-save-default nil)
(setq visible-bell t)
(setq use-dialog-box nil)
(setq global-auto-revert-non-file-buffers t)
(setq dictionary-server "localhost")
(setq next-line-add-newlines t)
(add-hook 'before-save-hook 'delete-trailing-lines)
(add-hook 'before-save-hook 'delete-trailing-whitespace)

(provide 'init-misc)
